In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

In [2]:
df =pd.read_json("News_Category_Dataset_v3.json",lines=True)

In [3]:
df.shape

(209527, 6)

In [4]:
df.describe()

                                date
count                         209527
mean   2015-04-30 00:44:14.344308736
min              2012-01-28 00:00:00
25%              2013-08-10 00:00:00
50%              2015-03-16 00:00:00
75%              2016-11-01 00:00:00
max              2022-09-23 00:00:00

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209527 entries, 0 to 209526
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   link               209527 non-null  object
 1   headline           209527 non-null  object
 2   category           209527 non-null  object
 3   short_description  209527 non-null  object
 4   authors            209527 non-null  object
 5   date               209527 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 9.6+ MB

In [6]:
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [7]:
df['text'] = df['headline'] + " " + df['short_description']

In [8]:
df = df[['text','category']]

In [9]:
df.head()

                                                text   category
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY
3  The Funniest Tweets From Parents This Week (Se...  PARENTING
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS

In [10]:
encoder = LabelEncoder()
df['category'] = encoder.fit_transform(df['category'])

In [11]:
X = df['text']
y = df['category']

In [12]:
df.head()

                                                text  category
0  Over 4 Million Americans Roll Up Sleeves For O...        35
1  American Airlines Flyer Charged, Banned For Li...        35
2  23 Of The Funniest Tweets About Cats And Dogs ...         5
3  The Funniest Tweets From Parents This Week (Se...        22
4  Woman Who Called Cops On Black Bird-Watcher Lo...        35

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=10000,
    ngram_range=(1,2)
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [15]:
model = MultinomialNB()
model.fit(X_train_vec,y_train)

MultinomialNB()

In [16]:
y_pred = model.predict(X_test_vec)
y_pred

array([38,  3, 24, ..., 17, 34,  3], shape=(41906,))

In [17]:
print("accuracy_score:",accuracy_score(y_test,y_pred))
print('classification_report',classification_report(y_test,y_pred))
print('confusion_matrix',confusion_matrix(y_test,y_pred))

accuracy_score: 0.5325729012551902
classification_report               precision    recall  f1-score   support

           0       0.50      0.02      0.04       293
           1       0.67      0.01      0.01       275
           2       0.62      0.16      0.25       889
           3       0.51      0.34      0.41      1216
           4       0.57      0.02      0.04       202
           5       0.62      0.25      0.36      1022
           6       0.51      0.51      0.51       713
           7       1.00      0.05      0.09       202
           8       0.83      0.46      0.59       664
           9       0.67      0.01      0.02       209
          10       0.48      0.79      0.60      3419
          11       0.97      0.11      0.19       313
          12       1.00      0.00      0.01       263
          13       0.58      0.74      0.65      1270
          14       0.80      0.03      0.06       270
          15       0.39      0.13      0.19       532
          16       0.52      0.04      0.08      1302
          17       0.82      0.52      0.64       879
          18       0.52      0.12      0.19       673
          19       0.50      0.00      0.01       238
          20       0.74      0.13      0.22       607
          21       0.63      0.07      0.13       355
          22       0.43      0.60      0.50      1768
          23       0.82      0.05      0.10       795
          24       0.54      0.92      0.68      7155
          25       0.76      0.47      0.58      1262
          26       0.74      0.18      0.30       530
          27       0.81      0.20      0.32       424
          28       0.71      0.54      0.61      1014
          29       1.00      0.00      0.01       464
          30       0.68      0.76      0.72      1975
          31       0.00      0.00      0.00       427
          32       0.78      0.16      0.26       398
          33       0.51      0.34      0.41       741
          34       0.56      0.79      0.66      2021
          35       0.00      0.00      0.00       269
          36       0.83      0.55      0.66       709
          37       0.55      0.07      0.13       550
          38       0.42      0.87      0.57      3672
          39       0.67      0.13      0.21       727
          40       0.51      0.19      0.28       665
          41       0.51      0.07      0.12       534

    accuracy                           0.53     41906
   macro avg       0.63      0.27      0.30     41906
weighted avg       0.58      0.53      0.47     41906

confusion_matrix [[  6   0   1 ...   2   1   1]
 [  1   2   3 ...   2   0   0]
 [  0   0 139 ...   0   0   1]
 ...
 [  0   0   5 ...  93   0   1]
 [  0   0   0 ...   2 126   4]
 [  0   0   2 ...   2  17  38]]

/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
model = LogisticRegression(max_iter=1000)

In [20]:
model.fit(X_train_vec, y_train)

LogisticRegression(max_iter=1000)

In [21]:
y_pred = model.predict(X_test_vec)

In [22]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.5968835011692837
              precision    recall  f1-score   support

           0       0.39      0.19      0.26       293
           1       0.32      0.10      0.15       275
           2       0.51      0.34      0.41       889
           3       0.50      0.48      0.49      1216
           4       0.46      0.32      0.38       202
           5       0.56      0.38      0.46      1022
           6       0.54      0.54      0.54       713
           7       0.65      0.23      0.34       202
           8       0.80      0.66      0.72       664
           9       0.47      0.27      0.34       209
          10       0.55      0.77      0.64      3419
          11       0.62      0.19      0.30       313
          12       0.49      0.10      0.17       263
          13       0.60      0.73      0.66      1270
          14       0.46      0.13      0.20       270
          15       0.38      0.30      0.34       532
          16       0.42      0.22      0.29      1302
          17       0.73      0.68      0.71       879
          18       0.44      0.27      0.34       673
          19       0.78      0.24      0.36       238
          20       0.63      0.40      0.49       607
          21       0.54      0.32      0.40       355
          22       0.51      0.67      0.58      1768
          23       0.47      0.19      0.27       795
          24       0.67      0.86      0.75      7155
          25       0.77      0.63      0.69      1262
          26       0.62      0.40      0.49       530
          27       0.59      0.41      0.48       424
          28       0.69      0.66      0.68      1014
          29       0.56      0.17      0.26       464
          30       0.73      0.81      0.76      1975
          31       0.43      0.11      0.17       427
          32       0.56      0.42      0.48       398
          33       0.49      0.42      0.45       741
          34       0.66      0.79      0.72      2021
          35       0.50      0.06      0.11       269
          36       0.75      0.71      0.73       709
          37       0.40      0.24      0.30       550
          38       0.54      0.81      0.65      3672
          39       0.46      0.33      0.39       727
          40       0.45      0.30      0.36       665
          41       0.50      0.26      0.34       534

    accuracy                           0.60     41906
   macro avg       0.55      0.41      0.44     41906
weighted avg       0.58      0.60      0.57     41906