In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('glass.csv')

In [3]:
df.shape

(214, 10)

In [4]:
df.describe()

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
count,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000
mean,1.518365,13.407850,2.684533,1.444907,72.650935,0.497056,8.956963,0.175047,0.057009,2.780374
std,0.003037,0.816604,1.442408,0.499270,0.774546,0.652192,1.423153,0.497219,0.097439,2.103739
min,1.511150,10.730000,0.000000,0.290000,69.810000,0.000000,5.430000,0.000000,0.000000,1.000000
25%,1.516522,12.907500,2.115000,1.190000,72.280000,0.122500,8.240000,0.000000,0.000000,1.000000
50%,1.517680,13.300000,3.480000,1.360000,72.790000,0.555000,8.600000,0.000000,0.000000,2.000000
75%,1.519157,13.825000,3.600000,1.630000,73.087500,0.610000,9.172500,0.000000,0.100000,3.000000
max,1.533930,17.380000,4.490000,3.500000,75.410000,6.210000,16.190000,3.150000,0.510000,7.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64
dtypes: float64(9), int64(1)
memory usage: 16.8 KB

In [6]:
df.isnull().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [7]:
df.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [8]:
df['Type'].unique()

array([1, 2, 3, 5, 6, 7])

In [9]:
X = df.drop('Type',axis=1)
y = df['Type']

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
model1 = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred1))

print("\nClassification Report")
print(classification_report(y_test,y_pred1))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred1))

Accuracy: 0.6976744186046512

Classification Report
              precision    recall  f1-score   support

           1       0.62      0.91      0.74        11
           2       0.62      0.57      0.59        14
           3       0.00      0.00      0.00         3
           5       0.50      0.25      0.33         4
           6       1.00      1.00      1.00         3
           7       0.89      1.00      0.94         8

    accuracy                           0.70        43
   macro avg       0.60      0.62      0.60        43
weighted avg       0.64      0.70      0.66        43


Confusion Matrix
[[10  1  0  0  0  0]
 [ 5  8  0  1  0  0]
 [ 1  2  0  0  0  0]
 [ 0  2  0  1  0  1]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  8]]

/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [13]:
model2 = KNeighborsClassifier(n_neighbors=10,metric='manhattan')
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred2))

print("\nClassification Report")
print(classification_report(y_test,y_pred2))

print("\nConfusion Matrix")
print(confusion_matrix(y_test,y_pred2))

Accuracy: 0.6976744186046512

Classification Report
              precision    recall  f1-score   support

           1       0.61      1.00      0.76        11
           2       0.62      0.57      0.59        14
           3       0.00      0.00      0.00         3
           5       1.00      0.25      0.40         4
           6       1.00      0.67      0.80         3
           7       0.89      1.00      0.94         8

    accuracy                           0.70        43
   macro avg       0.69      0.58      0.58        43
weighted avg       0.68      0.70      0.66        43


Confusion Matrix
[[11  0  0  0  0  0]
 [ 6  8  0  0  0  0]
 [ 1  2  0  0  0  0]
 [ 0  3  0  1  0  0]
 [ 0  0  0  0  2  1]
 [ 0  0  0  0  0  8]]

/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/gaurikutakole/venvs/py310-dl/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [14]:
for k in range(1,21):

    model = KNeighborsClassifier(n_neighbors=k,metric='manhattan')
    model.fit(X_train,y_train)

    y_pred = model.predict(X_test)

    print(k,accuracy_score(y_test,y_pred))

1 0.7906976744186046
2 0.6744186046511628
3 0.7674418604651163
4 0.7674418604651163
5 0.7906976744186046
6 0.6976744186046512
7 0.7209302325581395
8 0.6976744186046512
9 0.6976744186046512
10 0.6976744186046512
11 0.6976744186046512
12 0.6511627906976745
13 0.6744186046511628
14 0.6511627906976745
15 0.6511627906976745
16 0.6511627906976745
17 0.627906976744186
18 0.627906976744186
19 0.627906976744186
20 0.627906976744186

In [15]:
for k in range(1,21):

    model = KNeighborsClassifier(n_neighbors=k,metric='euclidean')
    model.fit(X_train,y_train)

    y_pred = model.predict(X_test)

    print(k,accuracy_score(y_test,y_pred))

1 0.7674418604651163
2 0.6976744186046512
3 0.813953488372093
4 0.7209302325581395
5 0.6976744186046512
6 0.6511627906976745
7 0.7209302325581395
8 0.6976744186046512
9 0.6744186046511628
10 0.627906976744186
11 0.627906976744186
12 0.6511627906976745
13 0.6511627906976745
14 0.6744186046511628
15 0.6976744186046512
16 0.6976744186046512
17 0.7209302325581395
18 0.7209302325581395
19 0.7209302325581395
20 0.6976744186046512