In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC

In [4]:
df = pd.read_csv('Social_Network_Ads (1).csv')

In [5]:
df.shape

(400, 5)

In [6]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [8]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [9]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
df.drop(['User ID'],axis=1,inplace=True)
df['Gender'] = df['Gender'].map({'Male':1,'Female':0})

In [11]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
dtypes: int64(4)
memory usage: 12.6 KB

In [15]:
X = df.drop('Purchased',axis=1)
y = df['Purchased']

In [16]:
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
scaler= StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
model1 = SVC(kernel='linear')
model1.fit(X_train,y_train)
y_pred1 = model1.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred1))
print('classification_report:',classification_report(y_test,y_pred1))
print('confusion_matrix:',confusion_matrix(y_test,y_pred1))

accuracy_Score: 0.8625
classification_report:               precision    recall  f1-score   support

           0       0.85      0.96      0.90        52
           1       0.90      0.68      0.78        28

    accuracy                           0.86        80
   macro avg       0.88      0.82      0.84        80
weighted avg       0.87      0.86      0.86        80

confusion_matrix: [[50  2]
 [ 9 19]]

In [19]:
model2 = SVC(kernel='rbf')
model2.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred2))
print('classification_report:',classification_report(y_test,y_pred2))
print('confusion_matrix:',confusion_matrix(y_test,y_pred2))

accuracy_Score: 0.925
classification_report:               precision    recall  f1-score   support

           0       0.96      0.92      0.94        52
           1       0.87      0.93      0.90        28

    accuracy                           0.93        80
   macro avg       0.91      0.93      0.92        80
weighted avg       0.93      0.93      0.93        80

confusion_matrix: [[48  4]
 [ 2 26]]

In [20]:
model3 = SVC(kernel='poly')
model3.fit(X_train,y_train)
y_pred3 = model3.predict(X_test)
print('accuracy_Score:',accuracy_score(y_test,y_pred3))
print('classification_report:',classification_report(y_test,y_pred3))
print('confusion_matrix:',confusion_matrix(y_test,y_pred3))

accuracy_Score: 0.9125
classification_report:               precision    recall  f1-score   support

           0       0.88      1.00      0.94        52
           1       1.00      0.75      0.86        28

    accuracy                           0.91        80
   macro avg       0.94      0.88      0.90        80
weighted avg       0.92      0.91      0.91        80

confusion_matrix: [[52  0]
 [ 7 21]]

In [22]:
kernels = ['linear','rbf','poly']
for k in kernels:
    model = SVC(kernel=k)
    model.fit(X_train,y_train)
    print(k,model.score(X_test,y_test))

linear 0.8625
rbf 0.925
poly 0.9125