In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('creditcard.csv')
df.shape

(284807, 31)

In [3]:
df = df.sample(100000)

In [4]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,94846.342750,0.003598,-0.000221,0.002811,-0.000647,-0.001512,-0.000473,0.003116,-0.003539,-0.003003,...,0.000591,-0.000198,0.001749,0.001506,-0.000537,-0.000986,0.000540,0.000147,88.246213,0.001780
std,47494.227456,1.951700,1.625479,1.509465,1.416445,1.350365,1.318587,1.210588,1.188860,1.100610,...,0.744429,0.724219,0.578978,0.602215,0.518519,0.482548,0.399879,0.314708,233.565145,0.042153
min,0.000000,-41.928738,-40.803981,-32.965346,-5.683171,-35.182120,-23.496714,-43.557242,-50.943369,-13.320155,...,-22.797604,-8.887017,-26.429741,-2.824849,-4.564506,-2.068561,-22.565679,-11.710896,0.000000,0.000000
25%,54222.000000,-0.916329,-0.600304,-0.889575,-0.846300,-0.693334,-0.767750,-0.552130,-0.208792,-0.644766,...,-0.228129,-0.537040,-0.161353,-0.350314,-0.317206,-0.327660,-0.070399,-0.052652,5.720000,0.000000
50%,84633.000000,0.018501,0.064375,0.183665,-0.025116,-0.054992,-0.274690,0.042948,0.021658,-0.055169,...,-0.029552,0.005942,-0.011635,0.040788,0.012773,-0.053942,0.001294,0.011765,22.020000,0.000000
75%,139281.500000,1.314940,0.802115,1.026585,0.742266,0.609917,0.397759,0.571449,0.324415,0.592847,...,0.184743,0.527545,0.147364,0.437349,0.350229,0.240052,0.090839,0.078822,77.850000,0.000000
max,172788.000000,2.454930,22.057729,9.382558,12.699542,34.099309,21.550496,36.877368,19.587773,15.594995,...,27.202839,8.316275,19.002942,4.022866,5.541598,3.517346,9.879903,16.129609,7879.420000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 235909 to 185407
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    100000 non-null  float64
 1   V1      100000 non-null  float64
 2   V2      100000 non-null  float64
 3   V3      100000 non-null  float64
 4   V4      100000 non-null  float64
 5   V5      100000 non-null  float64
 6   V6      100000 non-null  float64
 7   V7      100000 non-null  float64
 8   V8      100000 non-null  float64
 9   V9      100000 non-null  float64
 10  V10     100000 non-null  float64
 11  V11     100000 non-null  float64
 12  V12     100000 non-null  float64
 13  V13     100000 non-null  float64
 14  V14     100000 non-null  float64
 15  V15     100000 non-null  float64
 16  V16     100000 non-null  float64
 17  V17     100000 non-null  float64
 18  V18     100000 non-null  float64
 19  V19     100000 non-null  float64
 20  V20     100000 non-null  float64
 21  V21     100000 non-null  float64
 22  V22     100000 non-null  float64
 23  V23     100000 non-null  float64
 24  V24     100000 non-null  float64
 25  V25     100000 non-null  float64
 26  V26     100000 non-null  float64
 27  V27     100000 non-null  float64
 28  V28     100000 non-null  float64
 29  Amount  100000 non-null  float64
 30  Class   100000 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 24.4 MB

In [6]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
235909,148591.0,-0.234402,0.744235,-0.148247,-0.458873,1.418879,-0.340152,0.737247,0.054580,-0.551439,...,-0.202643,-0.652847,0.026353,0.180489,-0.741590,0.159662,0.124207,0.206381,0.99,0
174454,121917.0,1.856396,-0.399703,0.119397,1.409651,-0.919354,-0.284708,-0.725872,0.081188,1.272775,...,0.064702,0.242280,0.243874,-0.083542,-0.366101,-0.755137,0.067100,-0.015096,45.00,0
108596,70979.0,-1.066315,0.076415,1.469536,-1.972596,-0.731938,-0.085212,-0.759232,0.722221,-1.163303,...,0.478972,1.089750,-0.316680,-0.482303,0.224183,-0.147709,0.212687,0.052793,24.99,0
57366,47881.0,1.194106,-0.008160,-0.239317,1.101530,0.420055,0.612733,0.024303,0.116510,0.518989,...,-0.182708,-0.406736,-0.255543,-1.330340,0.806587,-0.226749,0.025446,0.006092,43.91,0
214191,139570.0,-0.453796,0.438568,0.020780,-0.912701,1.454998,0.892562,0.753006,0.400232,-0.299214,...,-0.014010,0.169388,0.183572,-1.409614,-1.027316,0.254095,0.426697,0.252020,33.07,0

In [7]:
df['Class'].unique()

array([0, 1])

In [8]:
X = df.drop('Class',axis=1)
y = df['Class']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=442)

In [10]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
model1 = SVC(kernel='linear')
model1.fit(X_train_scaled,y_train)
y_pred1 = model1.predict(X_test_scaled)
print('accuracy_score:',accuracy_score(y_test,y_pred1))
print('classification_score:',classification_report(y_test,y_pred1))
print('confusion_matrix:',confusion_matrix(y_test,y_pred1))

accuracy_score: 0.9996
classification_score:               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.90      0.90      0.90        39

    accuracy                           1.00     20000
   macro avg       0.95      0.95      0.95     20000
weighted avg       1.00      1.00      1.00     20000

confusion_matrix: [[19957     4]
 [    4    35]]

In [14]:
model2 = SVC(kernel='rbf')
model2.fit(X_train_scaled,y_train)
y_pred2 = model2.predict(X_test_scaled)
print('accuracy_score:',accuracy_score(y_test,y_pred2))
print('classification_score:',classification_report(y_test,y_pred2))
print('confusion_matrix:',confusion_matrix(y_test,y_pred2))

accuracy_score: 0.99905
classification_score:               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.95      0.54      0.69        39

    accuracy                           1.00     20000
   macro avg       0.98      0.77      0.84     20000
weighted avg       1.00      1.00      1.00     20000

confusion_matrix: [[19960     1]
 [   18    21]]

In [15]:
model3 = SVC(kernel='poly')
model3.fit(X_train_scaled,y_train)
y_pred3 = model3.predict(X_test_scaled)
print('accuracy_score:',accuracy_score(y_test,y_pred3))
print('classification_score:',classification_report(y_test,y_pred3))
print('confusion_matrix:',confusion_matrix(y_test,y_pred3))

accuracy_score: 0.99925
classification_score:               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.90      0.69      0.78        39

    accuracy                           1.00     20000
   macro avg       0.95      0.85      0.89     20000
weighted avg       1.00      1.00      1.00     20000

confusion_matrix: [[19958     3]
 [   12    27]]

In [18]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train_scaled,y_train)
y_pred = model.predict(X_test_scaled)
print('accuracy_score:',accuracy_score(y_test,y_pred))
print('classification_score:',classification_report(y_test,y_pred))
print('confusion_matrix:',confusion_matrix(y_test,y_pred))

accuracy_score: 0.99635
classification_score:               precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.00      0.00      0.00        39

    accuracy                           1.00     20000
   macro avg       0.50      0.50      0.50     20000
weighted avg       1.00      1.00      1.00     20000

confusion_matrix: [[19927    34]
 [   39     0]]